#!/bin/bash
#PBS -P MMNMDA
#PBS -l select=1:ncpus=1:ngpus=1:mem=64gb

#PBS -l walltime=30:00:00
cd $PBS_O_WORKDIR

module load cuda

export SCHRODINGER=/project/MMNMDA/schrodinger/

"${SCHRODINGER}/utilities/multisim" -JOBNAME random4-4nf8-s688yrot1-dser-md_4 -maxjob 1 -cpu 1 -m random4-4nf8-s688yrot1-dser-md_4.msj -c random4-4nf8-s688yrot1-dser-md_4.cfg -description 'Molecular Dynamics' random4-4nf8-s688yrot1-dser-md_4.cms -mode umbrella -set 'stage[1].set_family.md.jlaunch_opt=["-gpu"]' -o random4-4nf8-s688yrot1-dser-md_4-out.cms -WAIT
