#!/bin/bash
#PBS -P MMNMDA
#PBS -l select=1:ncpus=1:ngpus=1:mem=64gb

#PBS -l walltime=40:00:00
cd $PBS_O_WORKDIR

module load cuda

export SCHRODINGER=/project/MMNMDA/schrodinger/

"${SCHRODINGER}/utilities/multisim" -JOBNAME 4nf8_s688y_gly-rotamer1 -maxjob 1 -cpu 1 -m 4nf8_s688y_gly-rotamer1.msj -c 4nf8_s688y_gly-rotamer1.cfg -description 'Molecular Dynamics' 4nf8_s688y_gly-rotamer1.cms -mode umbrella -set 'stage[1].set_family.md.jlaunch_opt=["-gpu"]' -o 4nf8_s688y_gly-rotamer1-out.cms -WAIT
